### ISSUE TITLE
Remove osdrawer references from src files 

### ISSUE THREAD

**Issue by Vidrep** [HaikuArchives/Shredder#6]
Eg. git-svn-id: http://svn.osdrawer.net/shredder@8 4b78d5f5-3f53-456b-9fd…

**Comment by humdingerb** [comment]
This was the commit message when those files were imported 9 years ago. It's not part of a source file. Am I missing something?

**Comment by janus2** [comment]
I grep of the project doesn't show any reference to osdrawer...
